daemons:
   'us-east':
      lat: '40.7128'
      lon: '74.0060'
   'us-west':
      lat: '37.7749'
      lon: '122.4194'
   'eu-west':
      lat: '74.0060'
      lon: '4.9041'
   'in':
      lat: '20.5937'
      lon: '78.9629'
   'au':
      lat: '25.2744'
      lon: '133.7751'
   'sg':
      lat: '1.3521'
      lon: '103.8198'